# -*- coding: utf-8 -*-
"""ClassroomUsageForecasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V8LUYjrmgvXcsMFO36Mqrm17kjHDQFvS
"""

!pip install pandas numpy matplotlib statsmodels

import pandas as pd

wifi_data = {
    "timestamp": pd.date_range("2025-01-01 08:00", periods=10, freq="h"),
    "room_id": ["C101"] * 10,
    "connected_devices": [12, 28, 42, 38, 15, 8, 30, 45, 40, 18]
}

wifi_df = pd.DataFrame(wifi_data)
wifi_df

energy_data = {
    "timestamp": pd.date_range("2025-01-01 08:00", periods=10, freq="H"),
    "room_id": ["C101"] * 10,
    "energy_kwh": [1.9, 2.7, 3.6, 3.4, 2.3, 1.8, 3.0, 3.8, 3.5, 2.4]
}

energy_df = pd.DataFrame(energy_data)
energy_df

df = pd.merge(wifi_df, energy_df, on=["timestamp", "room_id"])
df.set_index("timestamp", inplace=True)
df

import matplotlib.pyplot as plt

plt.figure(figsize=(10,4))
plt.plot(df.index, df["energy_kwh"], marker="o")
plt.title("Classroom Energy Usage Over Time")
plt.xlabel("Time")
plt.ylabel("Energy (kWh)")
plt.grid(True)
plt.show()

"""### Combined Energy Usage and Occupancy (Wi-Fi Devices)"""

fig, ax1 = plt.subplots(figsize=(12, 6))

# Plot Energy Usage on primary y-axis
color = 'tab:blue'
ax1.set_xlabel('Time')
ax1.set_ylabel('Energy (kWh)', color=color)
ax1.plot(df.index, df['energy_kwh'], color=color, marker='o', label='Energy Usage')
ax1.tick_params(axis='y', labelcolor=color)
ax1.grid(True, linestyle='--', alpha=0.7)

# Create a second y-axis for Connected Devices
ax2 = ax1.twinx()
color = 'tab:orange'
ax2.set_ylabel('Connected Devices', color=color)
ax2.plot(df.index, df['connected_devices'], color=color, marker='x', linestyle='--', label='Connected Devices')
ax2.tick_params(axis='y', labelcolor=color)

# Add title and legend
plt.title('Classroom Energy Usage vs. Connected Devices Over Time')
fig.legend(loc='upper left', bbox_to_anchor=(0.15, 0.9))

plt.tight_layout()
plt.show()

plt.figure(figsize=(12, 6))

# Plot actual energy usage as line and scatter points
plt.plot(energy_series, label='Actual Energy Usage', color='darkblue', linewidth=1.5)
plt.scatter(energy_series.index, energy_series.values, color='darkblue', zorder=5, s=50)

# Get the last historical timestamp for plotting the forecast from
last_historical_timestamp = energy_series.index[-1]
forecast_timestamp = last_historical_timestamp + pd.Timedelta(hours=1)

# Plot the forecast point
plt.plot(forecast_timestamp, forecast_mean, color='green', marker='D', markersize=8, linestyle='None', label='Next-Hour Forecast')

# Plot the confidence interval
plt.fill_between(
    [last_historical_timestamp, forecast_timestamp],
    conf_int.iloc[0],  # Lower bound
    conf_int.iloc[1],  # Upper bound
    color='lightgray', alpha=0.6, label='95% Confidence Interval'
)

# Add a vertical line to indicate the transition from actual to forecast
plt.axvline(x=last_historical_timestamp, color='gray', linestyle=':', linewidth=1.0, label='Last Actual Point')

plt.title('Enhanced Next-Hour Energy Forecast with Confidence Interval')
plt.xlabel('Time')
plt.ylabel('Energy (kWh)')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

plt.figure(figsize=(10,4))
plt.plot(df.index, df["connected_devices"], color="orange", marker="o")
plt.title("Classroom Occupancy (Wi-Fi Devices)")
plt.xlabel("Time")
plt.ylabel("Connected Devices")
plt.grid(True)
plt.show()

energy_series = df["energy_kwh"]
energy_series

energy_series = energy_series.rolling(window=2).mean().dropna()
energy_series

from statsmodels.tsa.arima.model import ARIMA

model = ARIMA(energy_series, order=(1,1,1))
model_fit = model.fit()

model_fit.summary()

forecast = model_fit.get_forecast(steps=1)

forecast_mean = forecast.predicted_mean.iloc[0]
conf_int = forecast.conf_int().iloc[0]

print("🔮 Next Hour Energy Forecast:", round(forecast_mean, 2), "kWh")
print("📉 Lower Bound:", round(conf_int[0], 2), "kWh")
print("📈 Upper Bound:", round(conf_int[1], 2), "kWh")

plt.figure(figsize=(10,4))
plt.plot(energy_series, label="Actual Energy Usage")
plt.axhline(forecast_mean, color="green", linestyle="--", label="Forecast")

plt.fill_between(
    [energy_series.index[-1], energy_series.index[-1] + pd.Timedelta(hours=1)],
    conf_int[0],
    conf_int[1],
    color="gray",
    alpha=0.3,
    label="Confidence Interval"
)

plt.title("Next-Hour Energy Forecast")
plt.legend()
plt.grid(True)
plt.show()

